### ISSUE TITLE
Wrapped signatures not highlighted

### ISSUE THREAD

**Issue by UnkindPartition** [dag/vim2hs#39]
I often use this style for long type signatures:

```
buildLib
  :: Verbosity -> PackageDescription -> LocalBuildInfo
  -> Library -> ComponentLocalBuildInfo -> IO ()
```

Currently vim2hs doesn't recognize this as a signature.

**Comment by UnkindPartition** [comment]
That highlights the type (the last 2 lines in the example), but the function name ("buildLib") is still of a different colour.

**Comment by dag** [comment]
The fix I come up with breaks top-level TH. I'm leaning towards disabling that TH highlighting by default; it's technically incomplete anyway (it assumes you start with an identifier, but technically any expression is valid). Thoughts?

**Comment by UnkindPartition** [comment]
Personally I won't miss that too much, as I use TH very rarely. But others may disagree.

How about adding an option to choose between these two alternatives?

**Comment by dag** [comment]
Such an option would be hard to test and maintain properly; I'd really prefer not to go that route.
