### ISSUE TITLE
Highlight data constructors ?

### ISSUE THREAD

**Issue by osa1** [dag/vim2hs#43]
For now data constructors are not highlighted. I was thinking it may be useful especially in pattern matching code, are there any particular reason to not behave data constructors differently than ordinary functions?

**Comment by dag** [comment]
Mainly because it's hard to distinguish between a data constructor, a type, and a module.  Actually thinking about it now, modules should be easy (require whitespace, Haskell does).  I think it's uglier for no real benefit, but I might experiment with it and maybe make it an option.

**Comment by osa1** [comment]
I just looked at how sublime text 2 handles this situation. It highlights types and data constructors nicely:

![st2hshighlighting](https://f.cloud.github.com/assets/448274/92705/01537a00-65ec-11e2-8eac-85e6a7abe098.png)

It highlights as a type only if it comes after `::` syntax. Otherwise it treats it as a data constructor.

Is there a way to do this in VimL ?

**Comment by dag** [comment]
Yes, and vim2hs is already doing it to some extent (type signatures are highlighted as a whole).  But it quickly breaks down, I think.  What about in-lined type annotations?  What about TH?  What about imports and exports?  What about data kinds?

I'm also not sure what it's useful for.  To me, syntax highlighting is useful for seeing the syntactic scope/context of things like strings, and for distinguishing syntax from identifiers (so you're less likely to try and make an operator named `->` or a function named `import`).  For most intents and purposes, data constructors are used like any other identifiers, and in any case they're already visually distinct by being capitalized.

FWIW I think the highlighting in that Sublime screenshot is made uglier and messier by the highlighting of data constructors.  It also seems to be broken, why is `exp` in the middle there highlighted as a type?  It also makes it easy to mistake `SFunCall args:xs` for `SFunCall (args:xs)` when it's actually `(SFunCall args):xs`, but maybe that's just me.

But yea I might make it an option for people who want it.

**Comment by osa1** [comment]
> Yes, and vim2hs is already doing it to some extent (type signatures are highlighted as a whole). But it quickly breaks down, I think. What about in-lined type annotations? What about TH? What about imports and exports? What about data kinds?

I was thinking, since `::` is a special syntax and cannot be used as function name, we can simply parse type names as identifiers coming after `::` and started with a capital letter. And all other identifiers starting with a capital letter are data constructors. I may be wrong though.

> It also seems to be broken, why is exp in the middle there highlighted as a type?

It's not broken, `exp` is highlighted as a built-in function. (though I agree it looks bad, if I have been using sublime text I'd remove that built-in functions from syntax file)

So highlighting data constructors are mostly a matter of taste, if you don't want to work on this, no problems. I experimented with vim2hs's highlighter regexes but I don't know Vim regexes so couldn't understand much of it. Maybe I can try something after learning Vim's regex syntax.

**Comment by dag** [comment]
Consider code like `(+) <$> (read "Just 5" :: Maybe Int) <*> Just 2`.  With your scheme `Just` would highlight as a type.  Even if we tracked parenthesis (which would probably make vim2hs even slower) that breaks down with operator precedence.

**Comment by osa1** [comment]
You're right. What I need is basically parsing with regex. I'm closing the issue.
