### ISSUE TITLE
Highlight hsc files as Haskell

### ISSUE THREAD

**Issue by ocharles** [dag/vim2hs#61]
`.hsc` files are for `hsc2hs` - but they are pretty much just Haskell code.

**Comment by dag** [comment]
For #45 I've been wanting to add proper filetypes for these "supersets" of Haskell, but I suppose for now and for vim2hs it might be better-than-nothing to just load the haskell filetype.

**Comment by ocharles** [comment]
That's what I'm doing right now and it's more adequate than no highlighting at all :) Want a pull request?

**Comment by dag** [comment]
Certainly!
